### ISSUE TITLE
getting this error help please

### ISSUE THREAD

**Issue by v9pt** [Bratah123/GuessTheAnime#1]
![image](https://user-images.githubusercontent.com/81993995/124351920-ecc1c080-dc05-11eb-9a49-1b977a503204.png)

**Comment by Bratah123** [comment]
This is weird, anyway to replicate this? I pushed some more changes, which probably doesn't fix this issue.
The only other error I can get similar to this is if you aren't connected to a VC.

Possible things that might have caused this: 
```
library versions: I.E. python, discord.py
Or the bot isn't in a voice channel when attempting to play a song! (which isn't a problem fixed yet I don't think)
```

**Comment by v9pt** [comment]
Nvm did some work and fixed it
